
version: "3.3"

services: 
  nifi-server:
    environment:
      SINGLE_USER_CREDENTIALS_USERNAME: user_nifi
      SINGLE_USER_CREDENTIALS_PASSWORD: HGd15bvfv8744ghbdhgdv7895agqERAo
    image: apache/nifi:1.19.0
    container_name: nifi-server
    ports:
      - "8443:8443"
    deploy:
      resources:
        limits:
          memory: 4G
    restart: on-failure
    volumes:
      - nifi-database_repository:/opt/nifi/nifi-current/database_repository
      - nifi-flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - nifi-content_repository:/opt/nifi/nifi-current/content_repository
      - nifi-provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - nifi-conf:/opt/nifi/nifi-current/conf
      - nifi-state:/opt/nifi/nifi-current/state
      - ./nifi/logs:/opt/nifi/nifi-current/logs
      - ./nifi/jdbc:/opt/nifi/nifi-current/jdbc
      - ./nifi/credentials:/opt/nifi/nifi-current/credentials
    networks:
      - nifi-network

volumes:
    nifi-database_repository:
    nifi-flowfile_repository:
    nifi-content_repository:
    nifi-provenance_repository:
    nifi-state:
    nifi-conf:

networks:
  nifi-network:
    driver: bridge
